<?php $cards = $this->getLoggedUserCards(); ?>
    <div class="page-title">
        <h1><?php echo $this->__('Saved credit cards'); ?></h1>
    </div>
<?php if (count($cards) == 0 ): ?>
    <div class="welcome-msg">
        <p><?php echo $this->__('No saved cards'); ?></p>
    </div>
<?php else: ?>
    <table class="data-table">
        <colgroup>
            <col>
            <col width="1">
            <col>
            <col width="1">
            <col width="1">
            <col width="1">
        </colgroup>
        <thead>
        <tr class="first last">
            <th><?php echo $this->__('Card number'); ?></th>
            <th class="date"><?php echo $this->__('Expiration date'); ?></th>
            <th><?php echo $this->__('Cart type'); ?>'</th>
            <th class="view">&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($cards as $card): ?>
            <tr class="odd">
                <td>**** **** **** <?php echo $card->getData('mask'); ?></td>
                <td class="date"><?php echo $card->getData('validity_month'); ?>
                    /<?php echo $card->getData('validity_year'); ?></td>
                <td><?php echo $card->getData('issuer'); ?></td>
                <td class="a-center view last">
                <span class="nobr">
                    <a href="<?php echo Mage::getUrl('bluepayment/customer/view', array('card_index' => $card->getData('card_index'))); ?>">
                        <?php echo $this->__('DELETE'); ?>
                    </a>
                </span>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>