<!--
/**
 * BlueMedia_BluePayment extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Design
 * @package        Template
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */

-->

<div class="page-title">
    <h1>Dziękujemy za złożenie zamówienia</h1>
</div>
<p>Otrzymasz e-mail z potwierdzeniem zamówienia wraz ze szczegółami dotyczącymi Twojego zamówienia i linkiem do
    śledzenia jego postępów.</p>

<div class="buttons-set">
    <button type="button" class="button" title="Kontynuuj zakupy" onclick="window.location='/'"><span><span>Kontynuuj zakupy</span></span>
    </button>
</div>