<div class="p_method_bluepayment" id="p_method_bluepayment_gateway">
    <?php $gatewaysList = $this->getGatewaysList() ?>
    <?php $showLogoFlag = Mage::helper('bluepayment/gateways')->showGatewayLogo(); ?>
    <h4 style="padding-top: 20px; padding-left: 30px;">Wybierz sposób płatności:</h4>
    <ul class="bluepayment-options-list" style="margin-left: 30px;">
        <?php if (Mage::getSingleton('customer/session')->isLoggedIn() && Mage::helper('bluepayment/gateways')->showAutoPayments()): ?>
            <?php $gatewayId = Mage::helper('bluepayment/gateways')->getOneClickGatewayId(); ?>
            <?php $gatewayName = "Płatność automatyczna [One-Click]"; ?>
            <?php $cardsList = $this->getUserCardList(); ?>
            <li class="bluepayment-option">
                <div class="bluepayment-input">
                    <input id="p_method_bluepayment_gateway_<?php echo $gatewayId; ?>"
                           type="radio"
                           value="<?php echo $gatewayId; ?>"
                           name="payment_method_bluepayment_gateway"
                           title="<?php echo $gatewayName; ?>"
                           required
                           class="validate-one-required-by-name"
                    />
                    <label for="p_method_bluepayment_gateway_<?php echo $gatewayId; ?>">
                        <?php if ($showLogoFlag): ?>
                            <img src="https://platnosci.bm.pl/pomoc/grafika/1500.gif"
                                 alt="<?php echo $gatewayName; ?>" style="height: 40px; vertical-align:middle;">
                        <?php endif; ?>
                        <span style="line-height: 40px;">
                            <?php echo $gatewayName; ?>
                        </span>
                    </label>
                    <label>

                    </label>
                    <div style="display: none; margin-left: 15px;" id="payment_method_bluepayment_auto_payment">
                        <?php foreach ($cardsList as $card): ?>
                            <label>
                                <input type="radio" value="<?php echo $card->getData('card_index'); ?>"
                                       name="payment_method_bluepayment_card_index"/>
                                Karta <?php echo $card->getData('issuer'); ?> **** ****
                                **** <?php echo $card->getData('mask'); ?>
                            </label><br/>
                        <?php endforeach; ?>
                        <label>
                            <input type="radio" value="-1" name="payment_method_bluepayment_card_index"/> Dodaj nową kartę
                        </label><br/>
                        <label style="margin-left: 15px; display: none;" id="payment_method_bluepayment_reg">
                            <input type="checkbox" value="1" name="payment_method_bluepayment_auto_payment"/>
                            Przeczytałem i akceptuje
                            <a href="#" style="margin: 0 0 0 6px;" target="_blank"> regulamin płatności automatycznych.</a>
                        </label>
                    </div>
                </div>
            </li>
        <?php endif; ?>
        <?php foreach ($gatewaysList as $gateway): ?>
            <?php $gatewayId = $gateway->getData('gateway_id'); ?>
            <?php $gatewayName = $gateway->getData('gateway_name'); ?>
            <li class="bluepayment-option">
                <div class="bluepayment-input">
                    <input id="p_method_bluepayment_gateway_<?php echo $gatewayId; ?>"
                           type="radio"
                           value="<?php echo $gatewayId; ?>"
                           name="payment_method_bluepayment_gateway"
                           title="<?php echo $gatewayName; ?>"
                           required
                           class="validate-one-required-by-name"
                    />
                    <label for="p_method_bluepayment_gateway_<?php echo $gatewayId; ?>">
                        <?php if ($showLogoFlag): ?>
                            <?php if ($gateway->getData('use_own_logo')): ?>

                                <?php
                                $logoPath = $gateway->getData('gateway_logo_path');
                                if ($logoPath && $logoPath != ''):
                                    $ownLogoUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $logoPath;
                                    ?>
                                    <img src="<?php echo $ownLogoUrl; ?>"
                                         alt="<?php echo $gatewayName; ?>" style="height: 40px; vertical-align:middle;">
                                <?php endif; ?>
                            <?php else: ?>
                                <img src="<?php echo $gateway->getData('gateway_logo_url'); ?>"
                                     alt="<?php echo $gatewayName; ?>" style="height: 40px; vertical-align:middle;">

                            <?php endif; ?>
                        <?php endif; ?>
                        <span style="line-height: 40px;">
                            <?php echo $gatewayName . ' [' . $gateway->getData('gateway_type') . ']'; ?>
                        </span>
                    </label>

                    <span> <?php $gateway->getData('gateway_description'); ?></span>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<script>
    //<![CDATA[
    var $gateways = jQuery('#p_method_bluepayment_gateway');
    jQuery(document).ready(function () {

        $interval = setInterval(function () {
            jQuery('#p_method_bluepayment_gateway').find('input').each(function () {
                jQuery(this).removeAttr('disabled');
            });
        }, 50);
        setTimeout(function () {
            clearInterval($interval);
        }, 1000);

        var $bluepaymentInput = jQuery('#p_method_bluepayment');
        if ($bluepaymentInput.length) {
            setDefauleDisplayGateways($bluepaymentInput);

//            jQuery('.input [name="payment[method]"]').each.change(function () {
//                showHideGateways();
//            });

            jQuery('input[name="payment[method]"]').change(function () {
                if (jQuery(this).val() === 'bluepayment') {
                    showGateways();
                } else {
                    hideGateways();
                }
            });
            jQuery('input[type=radio][name=payment_method_bluepayment_gateway]').change(function () {
                if (this.value == <?php echo Mage::helper('bluepayment/gateways')->getOneClickGatewayId(); ?>) {
                    jQuery('#payment_method_bluepayment_auto_payment').show();
                    jQuery('#payment_method_bluepayment_auto_payment input').attr('required', 'required');
                    showReg();
                }
                else {
                    jQuery('#payment_method_bluepayment_auto_payment').hide();
                    jQuery('#payment_method_bluepayment_auto_payment input').attr('required', false);
                }
            });
            jQuery('input[type=radio][name=payment_method_bluepayment_card_index]').change(function () {
                showReg();
            });
        }
    });

    function showReg(){
        var index_card = 0;
        var gateway = 0;

        jQuery.map(jQuery('#co-payment-form').serializeArray(), function(n, i){
            if (n['name'] == 'payment_method_bluepayment_gateway'){
                gateway = n['value'];
            } else if (n['name'] == 'payment_method_bluepayment_card_index'){
                index_card = n['value'];
            }
        });

        if (index_card == -1 && gateway == <?php echo Mage::helper('bluepayment/gateways')->getOneClickGatewayId(); ?>){
            jQuery('#payment_method_bluepayment_reg').show();
        } else {
            jQuery('#payment_method_bluepayment_reg').hide();
        }
    }

    function setDefauleDisplayGateways(input) {
        if ($gateways.length) {
            $gateways.find('input[type="radio"]').each(function () {
                jQuery(this).prop('disabled', false);
            });
            if (input.is(':checked')) {
                $gateways.show();
            } else {
                $gateways.hide();
            }
        }
    }

    function showGateways() {
        if ($gateways.length) {
            $gateways.find('input[type="radio"]').each(function () {
                jQuery(this).prop('disabled', false);
            });
            $gateways.show();
        }
    }
    function hideGateways() {
        if ($gateways.length) {
            $gateways.hide();
        }
    }

    //]]>
</script>