<div class="p_method_bluepayment" id="p_method_bluepayment_gateway">
    <?php $gatewaysList = $this->getGatewaysList() ?>
    <?php $showLogoFlag = Mage::helper('bluepayment/gateways')->showGatewayLogo(); ?>
    <h4 style="padding-top: 20px; padding-left: 30px;">Wybierz sposób płatności:</h4>
    <ul class="bluepayment-options-list" style="margin-left: 30px;">
        <?php foreach ($gatewaysList as $gateway): ?>
            <?php $gatewayId = $gateway->getData('gateway_id'); ?>
            <?php $gatewayName = $gateway->getData('gateway_name'); ?>
            <li class="bluepayment-option">
                <div class="bluepayment-input">
                    <input id="p_method_bluepayment_gateway_<?php echo $gatewayId; ?>"
                           type="radio"
                           value="<?php echo $gatewayId; ?>"
                           name="payment_method_bluepayment_gateway"
                           title="<?php echo $gatewayName; ?>"
                           required
                           class="validate-one-required-by-name"
                    />
                    <label for="p_method_bluepayment_gateway_<?php echo $gatewayId; ?>">
                        <?php if ($showLogoFlag): ?>
                            <?php if ($gateway->getData('use_own_logo')): ?>

                                <?php
                                $logoPath = $gateway->getData('gateway_logo_path');
                                if ($logoPath && $logoPath != ''):
                                    $ownLogoUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $logoPath;
                                    ?>
                                    <img src="<?php echo $ownLogoUrl; ?>"
                                         alt="<?php echo $gatewayName; ?>" style="height: 40px; vertical-align:middle;">
                                <?php endif; ?>
                            <?php else: ?>
                                <img src="<?php echo $gateway->getData('gateway_logo_url'); ?>"
                                     alt="<?php echo $gatewayName; ?>" style="height: 40px; vertical-align:middle;">

                            <?php endif; ?>
                        <?php endif; ?>
                        <span style="line-height: 40px;">
                            <?php echo $gatewayName; ?>
                        </span>
                    </label>

                    <span> <?php $gateway->getData('gateway_description'); ?></span>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<script>
    //<![CDATA[
    var $gateways = jQuery('#p_method_bluepayment_gateway');
    jQuery(document).ready(function () {

        $interval = setInterval(function () {
            jQuery('#p_method_bluepayment_gateway').find('input').each(function () {
                jQuery(this).removeAttr('disabled');
            });
        }, 50);
        setTimeout(function () {
            clearInterval($interval);
        }, 1000);

        var $bluepaymentInput = jQuery('#p_method_bluepayment');
        if ($bluepaymentInput.length) {
            setDefauleDisplayGateways($bluepaymentInput);

//            jQuery('.input [name="payment[method]"]').each.change(function () {
//                showHideGateways();
//            });

            jQuery('input[name="payment[method]"]').change(function () {
                if (jQuery(this).val() === 'bluepayment') {
                    showGateways();
                } else {
                    hideGateways();
                }
            });
        }
    });

    function setDefauleDisplayGateways(input) {
        if ($gateways.length) {
            $gateways.find('input[type="radio"]').each(function () {
                jQuery(this).prop('disabled', false);
            });
            if (input.is(':checked')) {
                $gateways.show();
            } else {
                $gateways.hide();
            }
        }
    }

    function showGateways() {
        if ($gateways.length) {
            $gateways.find('input[type="radio"]').each(function () {
                jQuery(this).prop('disabled', false);
            });
            $gateways.show();
        }
    }
    function hideGateways() {
        if ($gateways.length) {
            $gateways.hide();
        }
    }

    //]]>
</script>