<!--
/**
 * BlueMedia_BluePayment extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Design
 * @package        Template
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */

-->

<div class="page-title">
    <h1><?php echo $this->__('Thank you for placing the order'); ?></h1>
</div>
<p><?php echo $this->__('You\'ll get the e-mail with order confirmation, details of your order and a link to track its progess.'); ?></p>

<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('Continue shopping'); ?>" onclick="window.location='/'"><span><span><?php echo $this->__('Continue shopping'); ?></span></span>
    </button>
</div>
