<!--
/**
 * BlueMedia_BluePayment extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category       Design
 * @package        Template
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */

-->

<!--Unikatowy identyfikator-->
<?php $code = $this->getMethodCode(); ?>

<!--Adres do pliku z logo firmy-->
<?php $img = $this->getLogoSrc(); ?>
<?php $infoText = $this->getInfoText(); ?>

<?php if ($img): ?>
    <img src="<?php echo $img ?>" alt="Autopay Logo" style="height: 40px; vertical-align:middle;"/>
<?php endif; ?>
<span>
    <?php echo $infoText; ?>
</span>
